### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by jide** [RBND-studio/flows-js#186]
Hello,

I installed Flows and inited the package in my Next.js app.

But I get this error : 
chunk-KLGGRI2K.mjs:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')

Which leads to :
yield crypto.subtle.digest("SHA-384",t)

Any clue why ?

**Comment by jide** [comment]
This was because it was on an insecure domain, https://editor.skillfab.local:3000. But how can I use flows on such a local dev domain without using https ? Having to use https locally is not convenient.

**Comment by VojtechVidra** [comment]
Hi,

the issue is that the library uses WebCrypto API which is restricted to secure origin. This doesn't mean you have to use https, secure origin is considered also localhost with http. More info: https://stackoverflow.com/questions/46670556/how-to-enable-crypto-subtle-for-unsecure-origins-in-chrome/46671627#46671627

Hope this helps!

**Comment by jide** [comment]
Oh thanks, I wasn't aware of this whitelist, it's surprisingly hard to find when you look for this error.

That said, it could be nice to mention this on the docs.

**Comment by VojtechVidra** [comment]
Thanks, I didn't realize it could cause problems until you've created this issue. I will make sure we have it mentioned in the docs.
